0
1
raised ValueError()
ret was: None
raised OSError()
raised ValueError('generator already executing',)
raised ValueError('generator already executing',)
0
ignore CancelledError
1
raised CancelledError()
None
CancelledError()
CancelledError()
1
